<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.*" />
    <PackageReference Include="xunit" Version="2.*" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.*" />
  </ItemGroup>

  <ItemGroup>
    <None Include="*.c" CopyToOutputDirectory="PreserveNewest" />
    <None Include="*.cc" CopyToOutputDirectory="PreserveNewest" />
    <None Include="reference\**\*.obj" CopyToOutputDirectory="PreserveNewest" Link="reference\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

</Project>
